# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Build and Release uYouEnhanced

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "17.5"
        required: true
        type: string
      uyou_version:
        description: "uYou Version"
        default: "3.0.4"
        required: true
        type: string
      decrypted_youtube_url:
        description: "Direct URL of the decrypted YouTube IPA"
        default: ""
        required: true
        type: string
      bundle_id:
        description: "Modify the bundle ID"
        default: "com.google.ios.youtube"
        required: true
        type: string
      app_name:
        description: "Modify the app name"
        default: "YouTube"
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      upload_artifact:
        description: "Upload IPA as artifact"
        default: false
        required: false
        type: boolean
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.2.2
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.2.2
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.2.0
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          # First clone the SDK repository
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/aricloverALT/sdks/
          cd sdks
          
          # Let's see what's in the repository initially
          echo "==> Checking repository contents before sparse checkout:"
          ls -la
          
          # Perform the sparse checkout
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          
          # Check what files we got after checkout
          echo "==> Contents after sparse checkout:"
          ls -la
          
          # Create the destination directory if it doesn't exist
          mkdir -p $THEOS/sdks
          
          # Check the Theos directory structure
          echo "==> Current Theos directory structure:"
          ls -la $THEOS
          echo "==> Contents of Theos sdks directory (before moving):"
          ls -la $THEOS/sdks
          
          # Move the SDK files and verify the move
          mv *.sdk $THEOS/sdks || echo "Error: Failed to move SDK files"
          
          # Verify the final state
          echo "==> Final contents of Theos sdks directory:"
          ls -la $THEOS/sdks
          echo "==> Checking specific SDK path that will be used:"
          ls -la $THEOS/sdks/iPhoneOS${{ inputs.sdk_version }}.sdk || echo "SDK directory not found in expected location"
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.2.2
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Hash YT ipa url
        run: |
          URL_YT="$(jq -r '.inputs.decrypted_youtube_url' $GITHUB_EVENT_PATH)"
          echo ::add-mask::$URL_YT
          echo URL_YT=$URL_YT >> $GITHUB_ENV

      - name: Prepare YouTube iPA
        id: prepare_youtube
        run: |
          wget "$YOUTUBE_URL" --quiet --no-verbose -O main/YouTube.ipa
          cd ${{ github.workspace }}/main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT

        env:
          THEOS: ${{ github.workspace }}/theos
          YOUTUBE_URL: ${{ env.URL_YT }}

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          
          # First, let's verify that we're in the correct directory
          echo "==> Current working directory:"
          pwd
          
          # Let's check if Theos environment variable is set correctly
          echo "==> THEOS environment variable:"
          echo "$THEOS"
          
          # Now verify the SDK accessibility with the full path
          echo "==> Verifying SDK accessibility:"
          ls -la "/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/sdks/iPhoneOS${{ inputs.sdk_version }}.sdk/" || echo "Failed to list SDK directory"
          
          # Test SDK path resolution with the full path
          echo "==> Testing SDK path resolution:"
          realpath "/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/sdks/iPhoneOS${{ inputs.sdk_version }}.sdk/" || echo "Failed to resolve SDK path"
          
          # Let's also check the SDK directory permissions all the way up
          echo "==> Checking parent directory permissions:"
          ls -la "/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/sdks"
          
          # Now proceed with the original commands
          sed -i '' "30s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "29s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile
          sed -i '' "1s#.*#export TARGET = iphone:clang:${{ inputs.sdk_version }}:14.0#g" Makefile
          
          # Add verbose flag to make for more detailed output
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1 VERBOSE=1

      - name: Create Release
        if: ${{ inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
